### ISSUE TITLE
Research different mysql backend python libraries

### ISSUE THREAD

**Issue by worldwise001** [worldwise001/monograph#5]
There's a few out there. I know there's the mysql connector, but also SQLAlchemy. It would be nice to take a look at different libraries and evaluate pros/cons. A hard need is a migration system so that it's easy for folks to upgrade over time (e.g. look at flyway in java).

**Comment by emil-h-harvey** [comment]
There are many Python backends for SQL through *SQL connectors* and *ORMs*.

SQL connectors provide low-level access to SQL.

ORMs provide high-level (e.g., abstract, pythonic) access. ORMs can be easier to use (rather than switching beween SQL-languages and Python) and can assist in difficult procedures (e.g., schema migrations).

[This repo](https://github.com/sloria/PythonORMSleepy) has examples of different ORMs.

[Peewee](http://docs.peewee-orm.com/en/latest/) is a Python ORM. It aims to be small and intuitive to learn.
